name=VOIZ
version=5.2
company-website=https://www.voipiran.io
company-en=VOIPIRAN
company-fa=ویپ ایران
partner-website=https://akzwp.com
partner-website-alt=https://akzwp.ir
partner-en=AKZ
partner-fa=ای کی زد
partner-brand=AKZ
copyright-footer=VOIPIRAN | ویپ ایران + AKZ | akzwp.ir
